TITLE = "Project Njord: Rogue"
VERSION = "v0.1.0"
WINDOW_TITLE = TITLE + " " + VERSION
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900
ZOOM_LEVEL = 2
GAME_WIDTH = WINDOW_WIDTH / ZOOM_LEVEL
GAME_HEIGHT = WINDOW_HEIGHT / ZOOM_LEVEL